apiVersion: apps/v1
kind: Deployment
metadata:
  name: week_15_exam-app
  labels:
    app: week_15_exam-app
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: week_15_exam-app
  template:
    metadata:
      labels:
        app: week_15_exam-app
        tier: backend
    spec:
      containers:
      - name: week_15_exam-app
        image: image-registry.openshift-image-registry.svc:5000/yehudafreiman-dev/week_15_exam-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_HOST
          value: "mysql"


